spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
      console.enabled: true
      console.path: /h2-console

jwt:
  secret: 'myPersonalTokEn9z3255CFHMcQfTjfoo09barWnZ123r4u788x1AcDdsGKaNdRgUkXp2softwareEngineering'
  validity: 3600
