spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
      console.enabled: true
      console.path: /h2-console

jwt:
  secret: 'myPersonalTokEn9z3255CFHMcQfTjfoo09barWnZ123r4u788x1AcDdsGKaNdRgUkXp2softwareEngineering'
  validity: 3600
